modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "All Rights Reserved"
[[mods]]
modId = "hopo"
version = "1.3.5"
displayName = "HopoBetterMineshaft"
displayURL = "https://discord.gg/CZQthZJjPc"
displayTest = "IGNORE_SERVER_VERSION"
issueTrackerURL = 'https://discord.gg/CZQthZJjPc'
credits = "Hoponopono"
authors = "Hoponopono"
description = "A mod that makes your mineshaft exploration more fun and exciting."
logoFile="pack.png" 
