modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "All Rights Reserved"
[[mods]]
modId = "hoporp"
version = "1.4.9"
displayName = "HopoBetterRuinedPortals"
displayURL = "https://discord.gg/CZQthZJjPc"
displayTest = "IGNORE_SERVER_VERSION"
issueTrackerURL = 'https://discord.gg/CZQthZJjPc'
credits = "Hoponopono"
authors = "Hoponopono"
description = "A mod that improve how the portals look in your world"
logoFile="pack.png" 